"""The icon build step, and the loader that reads what it produces.

The icon is the one artefact in this program that is allowed to be missing, and
the one whose absence must never stop the window opening. Two properties
therefore dominate this file: the generator produces a container Windows and Qt
can actually read, and the loader degrades quietly when it has not been run.

There is a third, quieter property. The ``.ico`` is *derived* from the committed
master rather than committed beside it, so that the two cannot disagree about
what the program looks like (docs/DESIGN.md amendment #15 note 1). That only
holds while the generator's output path and the loader's search path are the
same path, so that is pinned below rather than left to memory.

Every expected value is hand-derived in the comment above it
(docs/method/METHOD.md section 4).
"""

from __future__ import annotations

import os
import struct
import zlib

# MUST precede any Qt import (docs/method/TOOLING.md).
os.environ["QT_QPA_PLATFORM"] = "offscreen"

from pathlib import Path  # noqa: E402

import pytest  # noqa: E402

from michspc.gui import icon  # noqa: E402
from michspc.gui.app import build_application  # noqa: E402
from tools import make_icon  # noqa: E402


@pytest.fixture(scope="module")
def qapp():
    """One QApplication for the module; a second in a process crashes the
    interpreter (docs/method/TOOLING.md)."""
    application = build_application(["michspc-tests"])
    yield application
    application.processEvents()


def png_bytes(width: int, height: int, rows: list[bytes]) -> bytes:
    """Assemble a minimal 8-bit RGBA PNG from raw, unfiltered scanlines.

    Written here rather than generated by the code under test, so the decoder
    below is checked against bytes this file chose.
    """

    def chunk(kind: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body))
            + kind
            + body
            + struct.pack(">I", zlib.crc32(kind + body) & 0xFFFFFFFF)
        )

    # colour type 6 (RGBA), bit depth 8, compression 0, filter 0, interlace 0
    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    raw = b"".join(b"\x00" + row for row in rows)  # filter type 0 per scanline
    return (
        b"\x89PNG\r\n\x1a\x0a"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )


# A 2x2 RGBA image, chosen so that every channel and the alpha behave
# differently under averaging:
#
#   (255,0,0,255)  opaque red        (0,255,0,255)  opaque green
#   (0,0,255,128)  half-alpha blue   (255,255,255,0) fully transparent white
TINY_ROWS = [
    bytes([255, 0, 0, 255, 0, 255, 0, 255]),
    bytes([0, 0, 255, 128, 255, 255, 255, 0]),
]


# --------------------------------------------------------------------------
# PNG decoding
# --------------------------------------------------------------------------


def test_the_decoder_returns_the_pixels_that_were_encoded():
    """Round trip against bytes this file wrote, not against the tool's own."""
    width, height, pixels = make_icon.decode_png_rgba8(png_bytes(2, 2, TINY_ROWS))

    assert (width, height) == (2, 2)
    assert bytes(pixels) == b"".join(TINY_ROWS)


def test_the_decoder_reverses_every_png_filter():
    """Filters 0-4, each producing the same known row.

    Hand-derived. The target row is four pixels of (10, 20, 30, 40) repeated,
    so with a 4-byte pixel every filter's predictor is exactly computable:

      Sub (1):     each byte minus the byte 4 back. First pixel has no left
                   neighbour, so it stays (10,20,30,40); the rest become 0.
      Up (2):      each byte minus the byte above. Row 0's predictor row is
                   zeros, so row 0 is stored as-is and row 1 becomes all 0.
      Average (3): row 1, predictor (left + above) >> 1. With left and above
                   both equal to the value itself, (v + v) >> 1 == v, so every
                   stored byte in row 1 is 0 except the first pixel, whose left
                   is 0: (0 + v) >> 1 == v >> 1, leaving v - (v >> 1).
      Paeth (4):   row 1, predictors left/above/upper-left all equal v for the
                   later pixels, so the stored byte is 0; the first pixel has
                   left = upper-left = 0 and above = v, so Paeth picks v (the
                   estimate 0 + v - 0 = v is nearest to above) and stores 0.
    """
    pixel = bytes([10, 20, 30, 40])
    row = pixel * 4

    # Filter 0 on both rows: the plain case.
    plain = make_icon.decode_png_rgba8(png_bytes(4, 2, [row, row]))[2]
    assert bytes(plain) == row * 2

    def decode_with_filters(scanlines: list[tuple[int, bytes]]) -> bytes:
        raw = b"".join(bytes([kind]) + data for kind, data in scanlines)
        return bytes(make_icon._unfilter(raw, len(row), len(scanlines)))

    # Sub: first pixel verbatim, the other three encoded as zero deltas.
    assert decode_with_filters([(1, pixel + bytes(12))]) == row
    # Up: row 0 verbatim (its predictor row is zeros), row 1 all zero deltas.
    assert decode_with_filters([(2, row), (2, bytes(16))]) == row * 2
    # Average: row 1's first pixel stores v - (v >> 1) = 10-5, 20-10, 30-15,
    # 40-20 = (5, 10, 15, 20); the rest store 0.
    assert (
        decode_with_filters([(0, row), (3, bytes([5, 10, 15, 20]) + bytes(12))])
        == row * 2
    )
    # Paeth: row 1 stores nothing but zeros and still reproduces the row.
    assert decode_with_filters([(0, row), (4, bytes(16))]) == row * 2


@pytest.mark.parametrize(
    "mutate,fragment",
    [
        # A palette PNG (colour type 3) has no alpha channel to build an icon
        # from, so it is refused rather than read as if it had one.
        (lambda h: h[:9] + bytes([3]) + h[10:], "colour type 3"),
        # 16 bits per channel: the decoder reads 8, and reading a 16-bit image
        # as 8-bit silently halves the picture.
        (lambda h: h[:8] + bytes([16]) + h[9:], "16 bits per channel"),
        # Adam7 interlacing stores the image as seven interleaved passes.
        (lambda h: h[:12] + bytes([1]), "interlaced"),
    ],
)
def test_the_decoder_refuses_an_image_it_cannot_read(mutate, fragment):
    """Each refusal names what it found (docs/method/METHOD.md section 5)."""
    data = bytearray(png_bytes(2, 2, TINY_ROWS))
    # The IHDR body is the 13 bytes after the 8-byte signature, the 4-byte
    # length and the 4-byte chunk type: offsets 16 to 28.
    data[16:29] = mutate(bytes(data[16:29]))

    with pytest.raises(make_icon.IconError) as raised:
        make_icon.decode_png_rgba8(bytes(data))
    assert fragment in str(raised.value)


def test_the_decoder_refuses_something_that_is_not_a_png():
    with pytest.raises(make_icon.IconError) as raised:
        make_icon.decode_png_rgba8(b"GIF89a not a png at all")
    assert "PNG signature" in str(raised.value)


# --------------------------------------------------------------------------
# Resampling
# --------------------------------------------------------------------------


def test_the_span_weights_are_the_area_each_output_sample_covers():
    """Hand-derived from the definition of an area average.

    Reducing 4 samples to 2: output sample 0 covers source [0, 2) and output
    sample 1 covers [2, 4). Each covers two whole source samples, so each weight
    is 1/2 and each span starts at 0 and 2.

    Reducing 3 to 2: scale is 1.5, so output 0 covers [0, 1.5) - all of source
    0 and half of source 1 - and output 1 covers [1.5, 3.0) - half of source 1
    and all of source 2. Normalised by the 1.5 samples each covers, the weights
    are (1/1.5, 0.5/1.5) = (2/3, 1/3) and (1/3, 2/3).
    """
    assert make_icon._spans(4, 2) == [(0, (0.5, 0.5)), (2, (0.5, 0.5))]

    spans = make_icon._spans(3, 2)
    assert [start for start, _ in spans] == [0, 1]
    assert spans[0][1] == pytest.approx((2 / 3, 1 / 3))
    assert spans[1][1] == pytest.approx((1 / 3, 2 / 3))
    # Every span is a true average: its weights sum to one.
    for _, weights in make_icon._spans(1024, 48):
        assert sum(weights) == pytest.approx(1.0)


def test_the_resampler_averages_with_alpha_premultiplied():
    """The 2x2 fixture reduced to one pixel. Hand-derived.

    Premultiplied channel sums, each source pixel weighted 1/4 (half in each
    direction):

      red   x alpha: 255*255 = 65025 from the red pixel alone
      green x alpha: 255*255 = 65025 from the green pixel alone
      blue  x alpha: 255*128 = 32640 from the half-alpha blue pixel
      alpha:         255 + 255 + 128 + 0 = 638

    times 1/4: (16256.25, 16256.25, 8160.0, 159.5)

    Dividing the colour back out of the alpha it carries:

      red   = 16256.25 / 159.5 = 101.9201 -> 102
      green = 101.9201                    -> 102
      blue  =  8160.00 / 159.5 =  51.1599 ->  51
      alpha =                     159.5   -> 160

    The fully transparent white pixel contributes nothing to the colour, which
    is the whole point of premultiplying: a plain RGB average would have pulled
    the result toward white by a quarter and put a pale fringe on the artwork's
    edges at 16 px.
    """
    _, _, pixels = make_icon.decode_png_rgba8(png_bytes(2, 2, TINY_ROWS))
    reduced = make_icon.resample_area(pixels, 2, 2, 1, 1)

    assert bytes(reduced) == bytes([102, 102, 51, 160])


def test_a_uniform_image_survives_reduction_exactly():
    """An area average of identical samples is that sample, to the byte.

    This is where a rounding or clamping slip would show: the weights sum to
    1 only to within a few ULPs in doubles, so 255 can average to just over
    255 and wrap to 0 without the clamp in _to_byte.
    """
    pixel = bytes([255, 255, 255, 255])
    rows = [pixel * 8 for _ in range(8)]
    _, _, pixels = make_icon.decode_png_rgba8(png_bytes(8, 8, rows))

    for size in (4, 3, 2, 1):
        reduced = make_icon.resample_area(pixels, 8, 8, size, size)
        assert bytes(reduced) == pixel * size * size


def test_the_resampler_refuses_to_enlarge():
    """Upscaling would invent detail the master does not have."""
    _, _, pixels = make_icon.decode_png_rgba8(png_bytes(2, 2, TINY_ROWS))
    with pytest.raises(make_icon.IconError) as raised:
        make_icon.resample_area(pixels, 2, 2, 4, 4)
    assert "only reduces" in str(raised.value)


# --------------------------------------------------------------------------
# The .ico container
# --------------------------------------------------------------------------


def read_ico_directory(data: bytes) -> list[dict]:
    """Parse an .ico's directory, independently of the writer."""
    reserved, kind, count = struct.unpack_from("<HHH", data, 0)
    if reserved != 0 or kind != 1:
        raise ValueError(f"not an icon file: reserved={reserved} type={kind}")

    entries = []
    for index in range(count):
        (width, height, colours, pad, planes, bits, length, offset) = (
            struct.unpack_from("<BBBBHHII", data, 6 + 16 * index)
        )
        entries.append(
            {
                "width": width or 256,  # 0 means 256
                "height": height or 256,
                "colours": colours,
                "pad": pad,
                "planes": planes,
                "bits": bits,
                "length": length,
                "offset": offset,
                "body": data[offset : offset + length],
            }
        )
    return entries


def test_the_ico_directory_is_laid_out_where_the_format_says():
    """Hand-derived from the ICONDIR/ICONDIRENTRY structures.

    One 16x16 image:

      ICONDIR       = 6 bytes (reserved, type, count)
      ICONDIRENTRY  = 16 bytes, so the image data starts at 6 + 16 = 22
      BITMAPINFOHEADER = 40 bytes
      colour bitmap = 16 * 16 * 4 = 1024 bytes of BGRA
      AND mask      = 1 bit per pixel, rows padded to 4 bytes:
                      ((16 + 31) // 32) * 4 = 4 bytes per row, 16 rows = 64
      image total   = 40 + 1024 + 64 = 1128
      file total    = 22 + 1128 = 1150
    """
    data = make_icon.build_ico({16: bytes(16 * 16 * 4)})

    assert len(data) == 1150
    (entry,) = read_ico_directory(data)
    assert entry["width"] == 16
    assert entry["height"] == 16
    assert entry["planes"] == 1
    assert entry["bits"] == 32
    assert entry["colours"] == 0
    assert entry["length"] == 1128
    assert entry["offset"] == 22

    # The DIB header describes the colour bitmap and the mask as one image, so
    # its height is twice the icon's (Microsoft's ICONIMAGE documentation).
    size, bmp_width, bmp_height, planes, bits, compression = struct.unpack_from(
        "<IiiHHI", entry["body"], 0
    )
    assert (size, bmp_width, bmp_height) == (40, 16, 32)
    assert (planes, bits, compression) == (1, 32, 0)


def test_a_256_pixel_entry_records_its_size_as_zero():
    """The directory's width and height are single bytes, so 256 is written as
    0 and every reader knows to expand it. Getting this wrong produces an icon
    Windows shows as 0x0."""
    data = make_icon.build_ico({256: bytes(256 * 256 * 4)})
    assert data[6] == 0  # width byte of the first entry
    assert data[7] == 0  # height byte
    assert read_ico_directory(data)[0]["width"] == 256


def test_the_colour_bitmap_is_bottom_up_bgra():
    """Hand-derived on a 2x2 whose four pixels are all different.

    The source rows, top-down RGBA, are the TINY_ROWS fixture. A DIB stores
    rows bottom-up and channels as B, G, R, A, so the first four bytes of the
    colour bitmap are the BOTTOM-left pixel - (0, 0, 255, 128), opaque-ish blue
    - written as B=255, G=0, R=0, A=128.
    """
    _, _, pixels = make_icon.decode_png_rgba8(png_bytes(2, 2, TINY_ROWS))
    body = make_icon.build_ico({2: bytes(pixels)})[6 + 16 :]
    colour = body[40:]

    assert tuple(colour[0:4]) == (255, 0, 0, 128)  # bottom-left, BGRA
    # bottom-right was fully transparent white: (255, 255, 255, 0)
    assert tuple(colour[4:8]) == (255, 255, 255, 0)
    # top-left was opaque red (255, 0, 0, 255) -> B=0, G=0, R=255, A=255
    assert tuple(colour[8:12]) == (0, 0, 255, 255)


def test_an_empty_icon_is_refused():
    with pytest.raises(make_icon.IconError):
        make_icon.build_ico({})


# --------------------------------------------------------------------------
# The build step, on the real master artwork
# --------------------------------------------------------------------------


def test_the_master_artwork_is_the_image_the_design_records():
    """docs/DESIGN.md amendment #15 note 1: 1024x1024, 8-bit RGBA.

    Read from the committed file, so replacing the artwork with something of a
    different shape fails here rather than producing a distorted icon.
    """
    width, height, pixels = make_icon.decode_png_rgba8(
        make_icon.MASTER_PNG.read_bytes()
    )
    assert (width, height) == (1024, 1024)
    assert len(pixels) == 1024 * 1024 * 4


def test_generating_from_the_master_produces_the_six_windows_sizes(tmp_path):
    """16, 32, 48, 64, 128, 256 - the sizes Windows asks for."""
    written = make_icon.generate(output=tmp_path / "coord-convert.ico")

    assert written.exists()
    # Nothing partial survives: the staged file is renamed, not left behind.
    assert [p.name for p in tmp_path.iterdir()] == ["coord-convert.ico"]

    entries = read_ico_directory(written.read_bytes())
    assert [e["width"] for e in entries] == list(sorted(make_icon.ICON_SIZES))
    for entry in entries:
        assert entry["height"] == entry["width"]
        assert entry["bits"] == 32
        # Each body is its 40-byte header, size*size*4 of BGRA, and a 1-bit
        # mask padded to 4 bytes a row.
        size = entry["width"]
        mask = ((size + 31) // 32) * 4 * size
        assert entry["length"] == 40 + size * size * 4 + mask


def test_qt_reads_every_size_out_of_the_generated_icon(qapp, tmp_path):
    """The consumer that matters most here reads it back.

    A container that parses in this file's own reader but not in Qt's would be
    a test agreeing with itself. QIcon is the shipped window icon's own loader.
    """
    from PySide6.QtGui import QIcon

    written = make_icon.generate(output=tmp_path / "coord-convert.ico")
    loaded = QIcon(str(written))

    assert loaded.isNull() is False
    sizes = sorted(size.width() for size in loaded.availableSizes())
    assert sizes == list(sorted(make_icon.ICON_SIZES))


def test_the_generator_refuses_a_master_that_is_not_there(tmp_path):
    with pytest.raises(make_icon.IconError) as raised:
        make_icon.generate(master=tmp_path / "no-such-art.png")
    assert "master artwork is missing" in str(raised.value)


# --------------------------------------------------------------------------
# The generator and the loader must agree about where the icon lives
# --------------------------------------------------------------------------


def test_the_loader_looks_exactly_where_the_generator_writes():
    """One authoritative path, checked rather than remembered.

    The whole reason the .ico is generated instead of committed is that a second
    copy would drift from the master (docs/DESIGN.md amendment #15 note 1). That
    argument only holds while the loader reads the file the build step writes,
    so a change to either path has to change both or fail here.
    """
    assert make_icon.DEFAULT_OUTPUT == icon.GENERATED_ICO
    assert make_icon.MASTER_PNG == icon.MASTER_PNG
    assert icon.GENERATED_ICO in icon.icon_candidates()
    assert icon.MASTER_PNG in icon.icon_candidates()


def test_the_generated_icon_is_preferred_over_the_master(tmp_path, monkeypatch):
    """The .ico carries six hand-sized renderings; the PNG is one 1024 px image
    Qt would have to scale. When both exist the derived one wins."""
    generated = tmp_path / "coord-convert.ico"
    generated.write_bytes(b"stand-in")
    master = tmp_path / "coord-convert-1024.png"
    master.write_bytes(b"stand-in")

    monkeypatch.setattr(icon, "GENERATED_ICO", generated)
    monkeypatch.setattr(icon, "MASTER_PNG", master)

    assert icon.icon_path() == generated


def test_the_master_is_the_fallback_when_the_build_step_has_not_run(
    tmp_path, monkeypatch
):
    """A fresh clone still shows the owner's artwork."""
    monkeypatch.setattr(icon, "GENERATED_ICO", tmp_path / "not-built.ico")
    assert icon.icon_path() == icon.MASTER_PNG


def test_a_frozen_bundle_looks_inside_itself_first(tmp_path, monkeypatch):
    """PyInstaller unpacks data beside the executable and points sys._MEIPASS at
    it; a frozen run must not read the developer's build folder
    (docs/method/TOOLING.md)."""
    monkeypatch.setattr(icon.sys, "_MEIPASS", str(tmp_path), raising=False)

    bundled = tmp_path / "assets" / "icon" / icon.GENERATED_ICO_NAME
    assert icon.icon_candidates()[0] == bundled

    bundled.parent.mkdir(parents=True)
    bundled.write_bytes(b"stand-in")
    assert icon.icon_path() == bundled


def test_the_loader_returns_a_null_icon_rather_than_raising(tmp_path, monkeypatch):
    """No artwork anywhere. The window still has to open.

    This is the one place in the program where falling back beats refusing:
    nothing about a coordinate depends on the icon, and refusing to launch over
    a missing decoration would be the tier sentence applied backwards.
    """
    monkeypatch.setattr(icon, "GENERATED_ICO", tmp_path / "not-built.ico")
    monkeypatch.setattr(icon, "MASTER_PNG", tmp_path / "no-master.png")

    assert icon.icon_path() is None
    assert icon.application_icon().isNull() is True


def test_the_path_helpers_are_not_vacuous():
    """Guard against the checks above passing because nothing was found.

    icon_candidates() returning an empty tuple would make several assertions
    above trivially true, so the shape is pinned here.
    """
    candidates = icon.icon_candidates()
    assert len(candidates) >= 2
    assert all(isinstance(path, Path) for path in candidates)
