# column headers to be appiled when the CoordSet object is exported
ID=RowID
srcDatum=Input_Ref_Frame
destDatum=Output_Ref_frame
srcVertDatum=Input_Geopot_Datum
destVertDatum=Output_Geopot_Datum
srcLat=Input_Lat(DD)
srcLatDms=Input_Lat(DMS)
srcLon=Input_Lon(DD)
srcLonDms=Input_Lon(DMS)
heightUnits=Height_Units
srcEht=Input_Eht
srcOrthoht=Input_Orthoht
destLat=Output_Lat(DD)
destLatDms=Output_Lat(DMS)
destLon=Output_Lon(DD)
destLonDms=Output_Lon(DMS)
destEht=Output_Eht
destOrthoht=Output_Orthoht
deltaLat=Lat_Change(m)
sigLat=Lat_Sigma(s)
sigLat_m=Lat_Sigma(m)
deltaLon=Lon_Change(m)
sigLon=Lon_Sigma(s)
sigLon_m=Lon_Sigma(m)
sigEht=Eht_sigma
sigOrthoht=Orthoht_Sigma
spcZone=SPCZone
spcNorthing_m=SPCNorth(m)
spcEasting_m=SPCEast(m)
spcNorthing_ift=SPCNorth(ift)
spcEasting_ift=SPCEast(ift)
spcConvergence=SPCConvergence
spcScaleFactor=SPCSF
spcCombinedFactor=SPCCF
spcDistortion=SPCDistortion
utmZone=UTMZone
utmNorthing=UTMNorth
utmEasting=UTMEast
utmConvergence=UTMConvergence
utmScaleFactor=UTMSF
utmCombinedFactor=UTMCF
utmDistortion=UTMDistortion
x=X
y=Y
z=Z
usng=USNG



