"""Compose report.md: prose plus numbers computed from comparison.csv."""
import csv
import collections
from pathlib import Path

HERE = Path(r"C:\claude-projects\coord-convert\review\ncat-crosscheck")
rows = list(csv.DictReader(open(HERE / "comparison.csv", encoding="utf-8")))

counts = collections.Counter(r["status"] for r in rows)
agg = collections.defaultdict(lambda: [0, 0.0, 0.0, 0.0])
for r in rows:
    a = agg[r["pipeline"]]
    a[0] += 1
    q = r["quantity"]
    if q in ("northing", "easting", "latitude_deg", "longitude_deg"):
        a[1] = max(a[1], abs(float(r["delta_m_equiv"])))
    elif "convergence" in q:
        a[2] = max(a[2], abs(float(r["delta"])))
    else:
        a[3] = max(a[3], abs(float(r["delta"])))

ORDER = ["geodetic->SPC 2111", "geodetic->SPC 2112", "geodetic->SPC 2113",
         "SPC->geodetic 2111", "SPC->geodetic 2112", "SPC->geodetic 2113",
         "zone 2111->2112", "zone 2112->2111", "zone 2112->2113",
         "zone 2113->2112", "zone 2111->2113", "zone 2113->2111"]

verdict_lines = []
for p in ORDER:
    c, lm, cv, f = agg[p]
    any_fail = any(r["pipeline"] == p and r["status"] != "PASS" for r in rows)
    verdict = "FAIL/BLOCKED - see comparison.csv" if any_fail else "**PASS**"
    verdict_lines.append(
        f"| {p} | 3 (m, ift, usft) | {c} | {verdict} | {lm:.4f} m | "
        f"{cv:.2f}\" | {f:.1e} |")
verdict_table = "\n".join(verdict_lines)

status_line = (f"**{len(rows)} comparisons, {counts.get('PASS', 0)} PASS, "
               f"{counts.get('FAIL', 0)} FAIL, "
               f"{counts.get('BLOCKED', 0)} BLOCKED.**")

REPORT = f"""# Live NCAT crosscheck - end-to-end pipeline verification

Date: 2026-08-06. Program: `michspc` at commit 222d64a (working tree
untouched). Truth sources: NGS NCAT API (`/api/ncat/llh`, `/api/ncat/spc`) and
the NGS geoid API (`/api/geoid/ght`, model GEOID18). Every truth value used in
`comparison.csv` traces to a verbatim raw JSON capture in `raw/` (one file per
query, named for the query). Zero fabricated values; zero missing truth values
(`raw/_failures.txt` reads "none"). This file is generated by `gen_report.py`;
the verdict table and totals are computed from `comparison.csv`, not typed.

## Verdict table

| Pipeline | Runs | Comparisons | Verdict | Max linear delta (m-equiv) | Max convergence delta | Max factor delta |
|---|---|---|---|---|---|---|
{verdict_table}

{status_line}

## Maximum observed delta per quantity class (all pipelines, all units)

| Quantity class | Max delta | Tolerance | Worst case |
|---|---|---|---|
| northing/easting, single-leg (m-equivalent) | 0.0005 m | 0.002 m | C2, geodetic->SPC 2112, m, easting |
| northing/easting, chained zone-to-zone (m-equivalent) | 0.0009 m | 0.004 m | C2, zone 2111->2112, m, northing |
| geodetic output lat/lon (m-equivalent) | 0.00047 m | 0.002 m | C4, SPC->geodetic 2112, latitude |
| grid scale factor | 0 (exact at 8 dp, every point) | 2e-8 | - |
| convergence | 0.00" (exact at 0.01", every point) | 0.02" | - |
| geoid separation | 0.001 m | 0.002 m | S2 (Cadillac); 3 other points also at 0.001 m |
| elevation factor | 4.4e-09 | 2e-8 (chosen; same class as scale factor) | C3, geodetic->SPC 2112 |
| combined factor | 5.7e-09 | 2e-8 (chosen) | NS, zone 2113->2111 |

Foot-unit tolerances were converted at the exact legal ratios: international
foot 0.3048 m exactly, US survey foot 1200/3937 m exactly (0.002 m ->
0.006562 ft; 0.004 m -> 0.013123 ft). `comparison.csv` records the raw delta
in the run's own unit and the meter-equivalent delta side by side.

## Program entry point and configuration

Every run went through the program's real file path - the exact seam the GUI
uses (`michspc/gui/window.py` lines 59, 508, 577):

1. A PNEZD input file written to `inputs/` (comma-separated, no header row).
2. `michspc.job.JobSettings(...)` -> `michspc.job.run(settings)` - the job
   reads the file itself via `michspc.fileio.pnezd.read`.
3. `michspc.fileio.exports.write_all(result, overwrite=True)` - produces the
   single ZIP deliverable in `outputs/<tag>/`.
4. The audit CSV (`<stem>_full.csv`) parsed OUT OF THE ZIP - never from
   in-memory objects.

No core math function was called anywhere in the harness. Per-run settings are
recorded verbatim in `run_log.txt` (36 runs). Common to every run:

- `longitude_convention = LongitudeConvention.NEGATIVE_WEST` ("negative west
  (-84.37)") - selected explicitly for every run; input longitudes written
  signed negative, matching NCAT. The program has no default, by design.
- `apply_geoid = True` (bundled GEOID18 tile `data/g2018u3.bin`).
- geodetic->SPC runs: `input_unit = m` (elevations in meters), `output_unit`
  cycled through m / ift / usft.
- SPC->geodetic and zone-to-zone runs: `input_unit = output_unit` cycled
  through m / ift / usft; input coordinates were NCAT's own printed values in
  that unit; elevations converted into the same unit at the exact ratios.

## Truth methodology

- geodetic -> SPC: `llh?lat=&lon=&inDatum=NAD83(2011)&outDatum=NAD83(2011)
  &spcZone=` (inDatum = outDatum keeps it a pure conversion). The response
  carries the SPC pair in all three units (`spcNorthing_m/_ift/_usft`),
  convergence in DMS, scale factor at 8 dp - compared directly per unit.
- SPC -> geodetic: the `/api/ncat/spc` endpoint, established empirically first
  (probes 1-4 in `raw/`): parameters `northing`, `easting`, `units`
  (m | ift | usft), `spcZone`, `inDatum`, `outDatum`; `units` names the unit
  of the INPUT northing/easting; the geodetic answer is `destLat`/`destLon` at
  1e-10 deg. Probing with a frozen-anchor coordinate triple recovered the
  anchor's lat/lon within 5e-10 deg per unit system - exactly the effect of
  the 0.001-unit input rounding - so the endpoint was accepted as a direct
  truth source. Each of the 36 SPC->geodetic truth queries fed NCAT's own
  printed coordinates in that unit back to `/spc`, so the truth carries the
  same input rounding the program's input file carries.
- zone-to-zone: NCAT has no direct mode, so truth is the chain
  `llh(point, source zone)` -> program converts that printed coordinate ->
  compared to `llh(point, target zone)`. The extra printed rounding of the
  source coordinate (<= 0.0005 m per axis, scaled by the projection) is why
  the chained tolerance is 0.004 m; observed maximum was 0.0009 m.
- geoid separation: `/api/geoid/ght?lat=&lon=`, model GEOID18 in every
  response, compared to the audit CSV's "Geoid height (m)".
- Pacing ~1 query/second, sequential, retry with backoff. 69 raw captures
  (16 llh + 13 ght + 36 spc + 4 probes), zero failures.

## Elevation / combined factor hand derivation

The audit CSV's elevation and combined factors were re-derived per point from
truth inputs, entirely outside the program:

    R  = 6,372,000 m   (the program's own cited constant,
                        michspc/spc/factors.py, NOAA Manual NOS NGS 5, PDF
                        p. 59 - used here as the derivation input, so the
                        check verifies the program applies its cited constant
                        correctly)
    N  = geoid API geoidHeight (GEOID18)
    H  = the point's chosen orthometric height
    h  = H + N
    EF = R / (R + h)
    CF = k_NCAT * EF   (k_NCAT = the llh response's spcScaleFactor)

Worked example, point S3 (Detroit, 42.3314, -83.0458, H = 183.000 m),
geodetic->SPC 2113, meters run (`raw/geoid_S3.json`, `raw/llh_S3_2113.json`):

    N  = -34.547 m
    h  = 183.000 + (-34.547) = 148.453 m                  (audit: 148.453)
    EF = 6372000 / (6372000 + 148.453) = 0.99997670283... (audit: 0.99997670)
    CF = 0.99995325 * 0.99997670283  = 0.99992995392...   (audit: 0.99992995)
    Audit "Combined factor (ppm)" = -70.0, consistent with 1 - CF = 70.0 ppm.

Program-vs-truth deltas for this row: EF 2.8e-09, CF 3.9e-09 - both below
print precision. Across all 234 factor comparisons the maxima were EF 4.4e-09
and CF 5.7e-09: the program's full-precision values round to the same 8
decimal places NCAT and the derivation produce.

One systematic contributor worth naming: the program interpolates its bundled
GEOID18 tile; NGS's service interpolates its own grid. The four points that
differed did so by exactly 0.001 m - the print quantum of both sides - and
this feeds < 2e-10 into EF. Immaterial.

## Anomalies, refusals, and observations

1. No NCAT refusals. Every point was accepted in every zone queried -
   including the NS pair point (44.65, -85.5), which lies outside both the
   North and South design bands, and which NCAT converted in both 2111 and
   2113 without complaint (its 2111 northing is negative: -13,694.788 m). No
   replacement points were needed.
2. Program warnings (correct behavior, not defects). The six N<->S
   zone-to-zone runs each produced one `outside-zone-extent` warning for NS
   ("the coordinate is computed correctly, but distortion grows...") -
   recorded verbatim in `warnings_observed.txt`. The conversion proceeded and
   matched NCAT to <= 0.0005 m. That is the designed warn-but-convert
   behavior for points outside a zone's intended area (DESIGN.md amendment
   #1). No other warnings appeared in any run.
3. NCAT printing flutter. NCAT's foot values show last-digit flutter across
   equivalent queries (e.g. `spcNorthing_usft` 528,419.075 via llh vs
   528,419.074 via spc for the same physical point - probe 1 vs probe 2).
   Pure output rounding at the 0.3 mm level; absorbed by the tolerances.
4. Negative-northing input handled. The 2111->2113 runs fed a negative source
   northing (-13,694.788 m and its foot equivalents) through the full file
   path; parsed, converted, and matched NCAT truth.
5. Every unit system exercised on both sides of the file boundary. Input
   files in m/ift/usft for SPC-side inputs, outputs in m/ift/usft for
   SPC-side outputs, with NCAT's own per-unit printed values as truth, so the
   program's exact-ratio unit handling (0.3048; 1200/3937) is verified
   against NCAT's, not just internally.

## Files

- `raw/` - 69 verbatim JSON captures + `_failures.txt` ("none").
- `points.md` - the 12 points + NS, with rationale.
- `comparison.csv` - {len(rows)} rows: point, pipeline, unit, quantity,
  program value, truth value, delta, meter-equivalent delta, tolerance,
  PASS/FAIL, truth file.
- `run_log.txt` - the 36 job runs with full settings.
- `warnings_observed.txt` - the 6 program warnings, verbatim.
- `probe.py`, `fetch_truth.py`, `run_compare.py`, `points_def.py`,
  `gen_report.py` - the scripts, rerunnable.
- `inputs/`, `outputs/` - the 36 PNEZD input files and 36 ZIP deliverables.

## Bottom line

Every conversion pipeline, driven end to end through the real file path
(input file -> `job.run` -> ZIP -> audit CSV), agrees with NGS NCAT to within
half a millimeter single-leg and under one millimeter chained, with grid scale
factors and convergence angles matching NCAT's printed output exactly at every
one of the 12 fresh points, and elevation/combined factors matching an
independent hand derivation to ~5e-09. No FAIL, no BLOCKED, no fabricated
values.
"""

(HERE / "report.md").write_text(REPORT, encoding="utf-8")
print("report.md written,", len(REPORT.splitlines()), "lines")
